version: '3'
services:

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: test_task_jitouch_app
        image: test_task_jitouch_app
        restart: unless-stopped
        tty: true
        expose:
            - "9000"
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/test-task-ji-touch/app
        volumes:
            - ./:/var/www/test-task-ji-touch/app
            - ./_docker/app/local.ini:/usr/local/etc/php/conf.d/local.ini
        depends_on:
            - db
        networks:
            - test_task_jitouch_bridge

    webserver:
        image: nginx:alpine
        container_name: test_task_jitouch_webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./_docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
            - ./:/var/www/test-task-ji-touch/app
        environment:
            SERVER_NAME: "localhost"
            APP_PUBLIC_PATH: "/var/www/test-task-ji-touch/app/public"
            APP_CONTAINER_NAME: "test_task_jitouch_app"
            APP_PORT: "9000"
        depends_on:
            - app
        networks:
            - test_task_jitouch_bridge

    db:
        image: mysql:8.0
        container_name: test_task_jitouch_db
        restart: unless-stopped
        tty: true
        ports:
            - "${DB_PORT}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        volumes:
            - ./_docker/mysql:/docker-entrypoint-initdb.d
            - test_task_jitouch_dbdata:/var/lib/mysql/
        env_file:
            - .env
        networks:
            - test_task_jitouch_bridge

networks:
    test_task_jitouch_bridge:
        driver: bridge

volumes:
    test_task_jitouch_dbdata:
        driver: local
